### ISSUE TITLE
Edit function: Wrong example in error message

### ISSUE THREAD

**Issue by cs2113-bot-feedback** [CS2113-AY1819S1-W13-4/main#110]
**Describe the bug**
Wrong example in error message for the edit function

**To Reproduce**
1. Sign in as owner
2. Enter "edit 0 p/10"
3. Error message shown as 
"Invalid command format! 
edit: Edits the details of the book identified by the index number used in the displayed book list. Existing values will be overwritten by the input values.
Parameters: INDEX (must be a positive integer) [n/NAME] [i/ISBN] [p/PRICE] [c/COST] [t/TAG]...
Example: edit 1 i/978-3-16-148410-0 p/johndoe@example.com"
4. Use the sample example. Error message is show as
"Prices should be numerical and in 2 decimal places or none at all
E.g. $4, $3.02"

**Expected behavior**
Give an error message with a correct example.
Alternatively, feedback that it is an invalid index.

**Screenshots**
![screenshot 2018-11-02 17 31 36](https://user-images.githubusercontent.com/35737569/47907138-9be1f300-dec5-11e8-8de8-deef0bce384a.png)
![screenshot 2018-11-02 17 31 48](https://user-images.githubusercontent.com/35737569/47907139-9be1f300-dec5-11e8-8794-e713fd85e789.png)

<hr>

**Reported by:** @c-e-ooi
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#405]</sub>

**Comment by kohjunkiat** [comment]
@C-E-OOI

Thank you for your bug report regarding our **edit command's error message**

I have looked into the bug as mentioned, the first error message appear because **you've entered an invalid index number "0"**. 

Thank you for reporting this bug!
Jun Kiat
