### ISSUE TITLE
Request command showing invalid ISBN number 

### ISSUE THREAD

**Issue by cs2113-bot-feedback** [CS2113-AY1819S1-W13-4/main#111]
**Describe the bug**
When using the request command, i typed "request i/1234567890 e/helllo@example.com q/1" and it showed me that ISBN should be a valid 10-digit or 13-digit number. I provided a 10 digit number but my command got rejected. 

**To Reproduce**
1. Type request i/1234567890 e/helllo@example.com q/1

**Expected behavior**
I expect to see that the message to show that the ISBN number provided is not within the bookinventory.

**Screenshots**
![image](https://user-images.githubusercontent.com/35759184/47907175-ad2aff80-dec5-11e8-9aa2-8c970c2e8999.png)

**Additional context**

<hr>

**Reported by:** @limyisheng
**Severity:** `Medium`

<sub>[original: nusCS2113-AY1819S1/pe-1#407]</sub>

**Comment by kohjunkiat** [comment]
@LimYiSheng

Thank you for your bug report regarding our **request command's error message.**

I have looked into the _bug_ as mentioned, and unfortunately **this was the intended behavior**. ISBN has a specified format just like car plates, nric and etc. As such your input 1234567890 is not a _valid_ ISBN. We could have better phrase our error message.

Thank you for reporting this bug!
Jun Kiat
